apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app-deployment
spec:
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app-container
        image: registry.localhost:5000/vue-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
