apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rails-app-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rails-app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
