apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rails-app-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app-container
          image: registry.localhost:5000/rails-app:v1
          ports:
            - containerPort: 3000
