apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vue-app-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app-container
          image: registry.localhost:5000/vue-app:v2
          ports:
            - containerPort: 80
